# Generated by Django 4.2.1 on 2023-05-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_photo_userconfirmationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='AUTH_STATUS',
            new_name='auth_status',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='AUTH_TYPE',
            new_name='auth_type',
        ),
    ]
