# Generated by Django 4.2.1 on 2023-05-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_auth_status_usermodel_auth_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmationmodel',
            old_name='is_cinfirmed',
            new_name='is_confirmed',
        ),
    ]
