# Generated by Django 4.2.1 on 2023-05-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_cinfirmed_userconfirmationmodel_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='auth_status',
            field=models.CharField(choices=[('new', 'new'), ('code_verified', 'code_verified'), ('done', 'done'), ('photo_done', 'photo_done')], default='new', max_length=31),
        ),
    ]
